javascript: update C++ standard to C++17 for compatibility with newer Node.js versions
When compiling mraa on Debian 13, the following error occurs:

```
/usr/include/node/node.h:696:8: error: ‘optional’ in namespace ‘std’ does not name a template type
  696 |   std::optional<std::string> builder_script_path;
      |        ^~~~~~~~
/usr/include/node/node.h:696:3: note: ‘std::optional’ is only available from C++17 onwards
  696 |   std::optional<std::string> builder_script_path;
      |   ^~~
```

Root cause: Node.js version on Debian 13 is 20+, which requires C++17 feature support.

Signed-off-by: Chun Jiao Zhao <chunjiao.zhao@siemens.com>